/* test_xxh3.c - XXH3-64 (seed 0) against the reference digest
 *
 * The vectors are the contract: they were generated by the reference
 * implementation (Cyan4973/xxHash via the xxhash Python binding,
 * which wraps the reference C library), NOT by nevermore's own code,
 * so this test can fail. Coverage deliberately includes the regions
 * a partial implementation tends to get wrong:
 *
 *   - the official known-answer values (independent of any port);
 *   - every algorithm boundary: 0/1/2/3/4/8/9/16/17, 32/33, 64/65,
 *     96/97, 127/128/129/130, 239/240/241, and the 1024/1025 block
 *     edge — the last 64 bytes of the large path overlap earlier
 *     stripes, which is exactly where an off-by-one hides;
 *   - the conversation-id shapes the Hyper affinity headers actually
 *     hash (a UUID and nevermore's "nm-"+32hex form), so the wire
 *     value is pinned, not just the algorithm.
 *
 * House test conventions: RUN_TEST/ASSERT_*, NUL-termination before
 * ASSERT_STR_EQ, no real network (this is pure C).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "test_helpers.h"
#include "xxh3.h"

/* The official XXH3-64 known-answer values (Cyan4973/xxHash test
 * suite). These are independent of every implementation. */
static const char *const kat_inputs[] = {
    "",
    "a",
    "abc",
    "message digest",
    "abcdefghijklmnopqrstuvwxyz",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
    "12345678901234567890123456789012345678901234567890123456789012345678901234567890",
};
static const char *const kat_expected[] = {
    "2d06800538d394c2",
    "e6c632b61e964e1f",
    "78af5f94892f3950",
    "160d8e9329be94f9",
    "810f9ca067fbb90c",
    "643542bb51639cb2",
    "7f58aa2520c681f9",
};

/* Boundary lengths with a deterministic pattern (byte i =
 * (i*7+11) & 0xff), covering all three algorithm sections and their
 * subdivision edges. Expected values from the reference. */
typedef struct
{
    size_t len;
    const char *hex;
} Vec;

static const Vec vecs[] = {
    { 0, "2d06800538d394c2" },
    { 1, "4a4139caf4136257" },
    { 2, "5624b807618b3e87" },
    { 3, "dddcf0c53dcc6626" },
    { 4, "672a9b20285bc6fa" },
    { 5, "757f3b6e871fdd3c" },
    { 6, "6cc1d77286daa17c" },
    { 7, "a5837b8163e64c0e" },
    { 8, "c699dfbd5e59f215" },
    { 9, "784d9e4f6568d17b" },
    { 15, "5a8c87c027504b7c" },
    { 16, "ab1ea946d7ce63ee" },
    { 17, "d74f017b9724f65c" },
    { 18, "c2bc94373a1469b3" },
    { 31, "65d938d29a227049" },
    { 32, "ac211637b4afb1a1" },
    { 33, "355571a0279273c6" },
    { 47, "6e682e85e6145452" },
    { 48, "82dfc12a15e66a31" },
    { 49, "9fd069c1c0db4f3e" },
    { 63, "5fa7c4a65e9e4efc" },
    { 64, "972456007997a8f0" },
    { 65, "88760c4804f60006" },
    { 95, "1d9b5fd21e3b43f4" },
    { 96, "1e19381bf5b38a98" },
    { 97, "d68625d7a7047fe9" },
    { 127, "1be3f35de5843108" },
    { 128, "350400898b81d00a" },
    { 129, "7ea826cec195ec2d" },
    { 130, "72f5126a2e943c3f" },
    { 143, "236b8cf6427bb449" },
    { 144, "e9be18f4e3fda371" },
    { 159, "c88fe7253a19108e" },
    { 160, "fda12f3ce3f8a16a" },
    { 175, "2da986e0703dd310" },
    { 191, "e3676fa0eb071425" },
    { 192, "7d1d410bb02d7086" },
    { 200, "fd66728544df5b22" },
    { 207, "c2e4d74489702e65" },
    { 223, "948843ec4b29b735" },
    { 224, "f201c444ecdce46d" },
    { 239, "fc75f4167431f328" },
    { 240, "7a64cd90662680d5" },
    { 241, "1d321287ba448640" },
    { 255, "6668045d043ee1ab" },
    { 256, "177a77210db14873" },
    { 257, "362d2e0c3e5f3477" },
    { 300, "c369ed7813ac3e10" },
    { 384, "dae16867e4fed835" },
    { 512, "7e8377ea9c965fa3" },
    { 1024, "7300e68a6e9e4f13" },
    { 1025, "579025ebc2302dfa" },
    { 2048, "0e9fb607ce2bfd23" },
};

/* Deterministic byte pattern shared by every Vec. */
static void pattern(unsigned char *buf, size_t len)
{
    for (size_t i = 0; i < len; i++)
        buf[i] = (unsigned char)((i * 7 + 11) & 0xff);
}

static void test_known_answers(void)
{
    for (size_t i = 0; i < sizeof(kat_inputs) / sizeof(kat_inputs[0]); i++) {
        char got[17];
        nm_xxh3_64_hex(kat_inputs[i], strlen(kat_inputs[i]), got);
        if (strcmp(got, kat_expected[i]) != 0) {
            fprintf(stderr, "  KAT %zu: got %s want %s\n", i, got,
                    kat_expected[i]);
            test_fail_count++;
        }
    }
}

static void test_boundary_lengths(void)
{
    unsigned char buf[2048];
    pattern(buf, sizeof(buf));
    for (size_t i = 0; i < sizeof(vecs) / sizeof(vecs[0]); i++) {
        char got[17];
        nm_xxh3_64_hex(buf, vecs[i].len, got);
        if (strcmp(got, vecs[i].hex) != 0) {
            fprintf(stderr, "  len %zu: got %s want %s\n", vecs[i].len, got,
                    vecs[i].hex);
            test_fail_count++;
        }
    }
}

/* nm_xxh3_64 and nm_xxh3_64_hex must agree (hex is a rendering, not a
 * second algorithm). */
static void test_hex_matches_raw(void)
{
    unsigned char buf[300];
    pattern(buf, sizeof(buf));
    char hex[17];
    nm_xxh3_64_hex(buf, sizeof(buf), hex);
    char raw[17];
    snprintf(raw, sizeof(raw), "%016llx",
             (unsigned long long)nm_xxh3_64(buf, sizeof(buf)));
    ASSERT_STR_EQ(hex, raw);
    ASSERT_EQ(strlen(hex), 16);
}

static void test_output_shape(void)
{
    const size_t lens[] = { 0, 1, 16, 17, 128, 129, 240, 241, 2048 };
    unsigned char buf[2048];
    pattern(buf, sizeof(buf));
    for (size_t i = 0; i < sizeof(lens) / sizeof(lens[0]); i++) {
        char hex[17];
        nm_xxh3_64_hex(buf, lens[i], hex);
        ASSERT_EQ(strlen(hex), 16);
        for (int j = 0; j < 16; j++)
            ASSERT_TRUE((hex[j] >= '0' && hex[j] <= '9') ||
                        (hex[j] >= 'a' && hex[j] <= 'f'));
    }
}

/* The exact strings the Hyper headers will hash: a UUID and
 * nevermore's conversation-id shape. Pins the wire value, so a
 * regression in the id format or the hash shows up here first. */
static void test_conversation_id_shapes(void)
{
    char hex[17];
    nm_xxh3_64_hex("f47ac10b-58cc-4372-a567-0e02b2c3d479", 36, hex);
    ASSERT_STR_EQ(hex, "db22027126414ba6");
    nm_xxh3_64_hex("nm-0123456789abcdef0123456789abcdef", 35, hex);
    ASSERT_STR_EQ(hex, "ed926fff3042616d");
}

/* Deterministic: hashing is a pure function of the bytes. */
static void test_deterministic(void)
{
    char a[17], b[17];
    for (size_t n = 0; n <= 2048; n += 97) {
        unsigned char buf[2048];
        pattern(buf, n);
        nm_xxh3_64_hex(buf, n, a);
        nm_xxh3_64_hex(buf, n, b);
        if (strcmp(a, b) != 0) {
            fprintf(stderr, "  len %zu not stable\n", n);
            test_fail_count++;
        }
    }
}

/* Distinct inputs must not collide on the vectors we exercise (a
 * smoke test for a stuck accumulator / ignored length). */
static void test_no_trivial_collisions(void)
{
    unsigned char buf[2048];
    pattern(buf, sizeof(buf));
    char prev[17] = { 0 };
    for (size_t i = 0; i < sizeof(vecs) / sizeof(vecs[0]); i++) {
        char got[17];
        nm_xxh3_64_hex(buf, vecs[i].len, got);
        if (i > 0 && vecs[i].len != vecs[i - 1].len &&
            strcmp(got, prev) == 0) {
            fprintf(stderr, "  len %zu collided with previous\n",
                    vecs[i].len);
            test_fail_count++;
        }
        memcpy(prev, got, sizeof(prev));
    }
}

int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;
    printf("test_xxh3:\n");
    RUN_TEST(test_known_answers);
    RUN_TEST(test_boundary_lengths);
    RUN_TEST(test_hex_matches_raw);
    RUN_TEST(test_output_shape);
    RUN_TEST(test_conversation_id_shapes);
    RUN_TEST(test_deterministic);
    RUN_TEST(test_no_trivial_collisions);
    TEST_SUMMARY();
}